### ISSUE TITLE
build doesn't work on windows: there are some issues with node_modules

### ISSUE THREAD

**Issue by MaherBTA** [axelor/axelor-open-suite#11778]
I get this error when I try to build the ERP on windows:
`axelor-erp\modules\axelor-open-suite\axelor-human-resource\.gradle\yarn\yarn-v1.22.19\yarn.cmd'' finished with non-zero exit value 1`

there are errors in the packages.json files of some third-party libraries under axelor-react-timesheet

**Comment by houssam2293** [comment]
you should replace "CI=false node scripts/build.js" with "set CI=false&&node scripts/build.js" on line 67 in the modules\axelor-open-suite\axelor-human-resource\src\main\axelor-react-timesheet\package.json file

PS : the same should be done for project module in modules\axelor-open-suite\axelor-project\src\main\task-editor\package.json
replace "CI=false GENERATE_SOURCEMAP=false react-scripts build" with "set CI=false&&set GENERATE_SOURCEMAP=false&&react-scripts build" on line 38

Good luck

**Comment by claudiucotan** [comment]
This is a known issue and there is a clear workaround, you may close this ticket.
