### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by Scoutink** [axelor/axelor-open-suite#12420]
I really like it. But it is by far the most complicated platform to deploy. Checked the 2 guides on the net, mostly windows or French. Three days into trying to deploy it on google cloud VM instance and it is impossible so I gave up. I had other ERPs deployed via plesk. This is unfortunate, tbh...

**Comment by Glitch-Trap-1** [comment]
Are you deploying it on Windows or Ubuntu? I haven't done windows yet but it works great in Ubuntu. Just download the .war file and place it under the /opt/tomcat/webapps/ROOT directory. Do a sudo jar xvf [filename] and it'll unpack everything. Go into the axelor-config.properties and make sure you input the correct database connection settings for the database you want Axelor ERP to use. Once you do a sudo systemctl restart tomcat and a sudo tail -f /opt/tomcat/logs/catalina.out

You can watch the logs and make sure it deploys perfectly. Make sure to configure the pg_hba.conf correctly in the PostgreSQL directory. It should work just fine. I have one production instance with it's own local domain name on a server and two instances for migration/new versions running at the same time using the same local domain name. You can use Nginx for SSL

**Comment by Scoutink** [comment]
@Glitch-Trap-1 

Appreciate the response. I am deploying it on Ubuntu (google cloud VM). I will give it another try following your recommendations this weekend.

Thanks for the tips.

**Comment by Scoutink** [comment]
@Glitch-Trap-1 The document will be great, certainly. I will try to deploy it during the weekend. You are very kind.

**Comment by Glitch-Trap-1** [comment]
Here is the .txt file for it. If something doesn't work out too well, let me know. Hopefully this guide will help others as well!


[AxelorERP installation guide.txt](https://github.com/axelor/axelor-open-suite/files/15044122/AxelorERP.installation.guide.txt)

**Comment by Scoutink** [comment]
Thanks @Glitch-Trap-1 that was really helpful. Is there a way you know to whitelabel the platform to personalize it, change login logo for example?

**Comment by Glitch-Trap-1** [comment]
Hey @Scoutink,

I changed the theme color and made my own theme not too long ago. If you go into the opt/tomcat/webapps/ROOT

You should see a bunch of files and directories, I would look into the login.jsp and common.jsp file for the login related stuff. The 16th line in the common.jsp file references "img/axelor.png".  You'll find the "img" directory under ROOT. Just add your new .png and you could probably change that. I know that the login.jsp references the common.jsp in some way. So it might change more than you would like. I haven't messed with that yet, but I definitely should!

**Comment by AVIORGEO** [comment]
I need some help with deploying Axelor open suite. I am a nebbie when it come to linux. I followed all the steps shared by [AxelorERP installation guide.txt](https://github.com/axelor/axelor-open-suite/files/15044122/AxelorERP.installation.guide.txt). When axelor is deployed I get an authentication for user axelor. I don't event have a user axelor, but to go around it i created this user but still getting aurthenication error. any help is much appreciated. org.postgresql.util.PSQLException: FATAL: password authentication failed for user "axelor"
