### ISSUE TITLE
Ventilation de facture en erreur - n° de série en cause

### ISSUE THREAD

**Issue by DtNeo** [axelor/axelor-open-suite#5386]
Bonjour,

**Erreur reproduite ce jour** (04/05/2020) sur la **démo en ligne en version: 5.3.4**
Egalement en erreur en local en version: 5.3.3,  depuis le 23/04/2020
Lien de mon post sur le forum : https://forum.axelor.com/t/erreur-lors-de-la-ventilation-de-la-facture/2878

**Reproduire l'erreur sur la démo en ligne :** 
Créer une commande et ajouter un client (peut importe lequel);
Ajouter la référence : [EQPT-0005] Imprimante Jet d'encre (référence ayant un n° de série);
Mettre la quantité à 5;
Confirmer tous les documents jusqu'à la validation (il ne devrait pas y avoir d'erreur).

L’erreur survient à la ventilation.
Les lignes dispatchées des n° de series ne correspondent pas à la ligne de facture avec une quantité de 5.

Merci pour tout ce que vous faites,
Bon courage à tous

Excellente journée

**Comment by ale-axelor** [comment]
Bonjour,

Cette erreur était dûe à une anomalie avec les numéros de suivis et nos changements pour permettre la facturation partielle d'un mouvement de stock.

De plus, gérer à la fois une facturation partielle des mouvements de stocks et séparer puis regrouper les lignes par numéro de suivi sur les factures n'est pas possible pour le moment.

La version 5.3.6 qui vient de sortir inclut la correction suivante : 
- deux configurations dans l'app supplychain sont créées, pour activer la facturation partielle respectivement dans les bon de livraisons et de réception.
- Si la facturation partielle des mouvements de stock est activée, alors on ne peut pas facturer les lignes séparées par les numéros de suivis dans le cas des livraisons.

Pour résoudre ici l'erreur, il faut passer sur la version 5.3.6 et laisser désactivé la facturation partielle sur les livraisons.

(référence des commits : c94f4da et 6c58bc7776)

**Comment by DtNeo** [comment]
Merci pour votre retour.

Je ne pense pas que ce soit une bonne chose de vouloir assigner les n° de série/lots (=LOTS) au niveau de la facturation. Je comprends bien que ce n'est pas simple et évident pour votre code, mais vouloir gérer les LOTS sur la facturation va être une tâche fastidieuse alors qu'elle n'est pas pertinente à ce niveau là (de mon point de vue).

Il ne me semble pas voir de LOTS sur les factures (au moins de mes fournisseurs). Pour moi ce n'est qu'au niveau du bon de livraison/réception que les LOTS sont à contrôler et uniquement là.

Pourquoi ne pas uniquement vérifier les quantités par référence produit et sur les références de documents des BL/BR pour chaque facture ?

BL1
1x ABCD - Produit1 - lot #1
1x ABCD - Produit1 - lot #2 
1x ABCD - Produit1 - lot #3 
1x ABCD - Produit1 - lot #4  

BL2
5x EFGH - Produit2

FC1 - facturation partielle
1x ABCD - Produit1 du BL1 (partiel)
5x EFGH - Produit2 du BL2 (total)

FC1 - facture de solde
3x ABCD - Produit1 du BL1 (total)

Bon courage à tous !

**Comment by ale-axelor** [comment]
Bonjour,

Nous sommes d'accord : c'est une limitation et dans l'idéal on voudrait tout gérer. Malheureusement, notre fonctionnement au niveau de la facturation fait que nous gérons tout par ligne. De plus, on pourrait avoir des cas plus complexes, avec des avoirs, des annulations et des facturations partielles de lignes de numéro de suivi. Notamment avoir une ligne de facture qui a facturée partiellement plusieurs lignes de mouvement de stock qui sont elle même

Gérer tous ces cas demande beaucoup de changements que nous ne réaliserons pas sur une version mineure.
