### ISSUE TITLE
Loop on isBlockedPartnerOrParent Method

### ISSUE THREAD

**Issue by manfredCorbeau** [axelor/axelor-open-suite#8891]
I'm having an issue with the isBlockedPartnerOrParent Method in the com.axelor.apps.supplychain.service package.

When a partner have a parent, the actual method recall the isBlockedPartnerOrParent methode by providing one more time partner, instead of partner parent.

I tried to fix that by recall the method with the partner parent, if there is one and partner is not blocked, and it seems to work.

Could you confirm me there is a problem with the actual method ?

**Comment by ale-axelor** [comment]
Hello,

Indeed there was an issue since this code appeared (version 6.2.0) and we merged the fix (#9276).
The correction will be available on the next correction versions (6.2.14, 6.3.6, 6.4.1)
